//! Compact, generated Nerd Fonts name catalog.
//!
//! `names.bin` is generated by `utils/gen_icons.py`. It contains two sorted
//! tables: every family-qualified name and the preferred glyph for every
//! bare name. Records are two little-endian `u32`s (name offset, codepoint);
//! names live in separate NUL-delimited blobs. This is substantially smaller
//! than a Rust `(&str, u32)` table, whose records occupy 24 bytes on 64-bit
//! targets before any string data.

const DATA: &[u8] = include_bytes!("names.bin");
const HEADER_LEN: usize = 28;
const RECORD_LEN: usize = 8;

#[derive(Clone, Copy)]
pub(super) struct Table {
    records: &'static [u8],
    names: &'static [u8],
}

impl Table {
    pub(super) fn len(self) -> usize {
        self.records.len() / RECORD_LEN
    }

    pub(super) fn get(self, index: usize) -> Option<(&'static str, u32)> {
        let record = self
            .records
            .get(index * RECORD_LEN..(index + 1) * RECORD_LEN)?;
        let offset = read_u32(record, 0) as usize;
        let codepoint = read_u32(record, 4);
        let tail = self.names.get(offset..)?;
        let length = tail.iter().position(|&byte| byte == 0)?;
        let name = std::str::from_utf8(&tail[..length]).ok()?;
        Some((name, codepoint))
    }

    pub(super) fn find(self, key: &str) -> Option<u32> {
        let mut left = 0;
        let mut right = self.len();
        while left < right {
            let middle = left + (right - left) / 2;
            let (name, codepoint) = self.get(middle)?;
            match name.cmp(key) {
                std::cmp::Ordering::Less => left = middle + 1,
                std::cmp::Ordering::Greater => right = middle,
                std::cmp::Ordering::Equal => return Some(codepoint),
            }
        }
        None
    }

    pub(super) fn iter(self) -> impl Iterator<Item = (&'static str, u32)> {
        (0..self.len()).filter_map(move |index| self.get(index))
    }
}

pub(super) fn qualified() -> Table {
    tables().0
}

pub(super) fn bare() -> Table {
    tables().1
}

fn tables() -> (Table, Table) {
    assert_eq!(&DATA[..4], b"IMIC", "invalid embedded icon catalog");
    let q_count = read_u32(DATA, 4) as usize;
    let q_record_len = read_u32(DATA, 8) as usize;
    let q_name_len = read_u32(DATA, 12) as usize;
    let b_count = read_u32(DATA, 16) as usize;
    let b_record_len = read_u32(DATA, 20) as usize;
    let b_name_len = read_u32(DATA, 24) as usize;
    assert_eq!(q_record_len, q_count * RECORD_LEN);
    assert_eq!(b_record_len, b_count * RECORD_LEN);

    let q_records_start = HEADER_LEN;
    let q_names_start = q_records_start + q_record_len;
    let b_records_start = q_names_start + q_name_len;
    let b_names_start = b_records_start + b_record_len;
    let end = b_names_start + b_name_len;
    assert_eq!(end, DATA.len(), "invalid embedded icon catalog lengths");

    (
        Table {
            records: &DATA[q_records_start..q_names_start],
            names: &DATA[q_names_start..b_records_start],
        },
        Table {
            records: &DATA[b_records_start..b_names_start],
            names: &DATA[b_names_start..end],
        },
    )
}

fn read_u32(bytes: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes(bytes[offset..offset + 4].try_into().expect("u32 field"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_is_well_formed_and_sorted() {
        for table in [qualified(), bare()] {
            assert!(table.len() > 0);
            let rows: Vec<_> = table.iter().collect();
            assert_eq!(rows.len(), table.len());
            assert!(rows.windows(2).all(|pair| pair[0].0 < pair[1].0));
            assert!(rows
                .iter()
                .all(|(_, codepoint)| char::from_u32(*codepoint).is_some()));
        }
    }
}
