#!/usr/bin/env python3
"""Regenerate src/icons/names.rs from the official Nerd Fonts glyph names.

Usage:
    utils/gen_icons.py [glyphnames.json] > src/icons/names.rs
    utils/gen_icons.py <url-or-path>     # fetch from the nerd-fonts repo

Without an argument the glyph names are downloaded from the nerd-fonts
master branch. The JSON is the one published for the cheat sheet
(https://www.nerdfonts.com/cheat-sheet) and is MIT licensed.

Two tables are emitted, both sorted by key and meant for binary search:

- QUALIFIED: every glyph under its full "<family><name>" key
  (e.g. "md-power_off" -> "mdpower"), the "nf-" prefix already stripped.
- BARE: the same glyphs under their family-less name ("poweroff"), with
  collisions between sets resolved by FAMILY_PREFERENCE (Material Design
  first: the largest and most consistent set, so unqualified names keep
  a uniform look inside a menu).

Normalization matches icons::normalize on the Rust side: lowercase, keep
[ae0-9] alphanumerics only, drop every separator.
"""

import json
import sys
import urllib.request

DEFAULT_URL = (
    "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/glyphnames.json"
)

# Which set wins when the same bare name exists in several (see module doc).
FAMILY_PREFERENCE = [
    "md",        # Material Design Icons — largest, most consistent set
    "fa",        # Font Awesome (classic names people know)
    "cod",       # VS Code codicons
    "oct",       # GitHub octicons
    "dev",       # Devicons
    "seti",
    "linux",
    "fae",
    "custom",
    "ple",
    "pom",
    "pl",
    "iec",
    "weather",
    "indent",
    "indentation",
    "extra",
]
RANK = {family: rank for rank, family in enumerate(FAMILY_PREFERENCE)}


def normalize(name: str) -> str:
    return "".join(c for c in name.lower() if c.isalnum())


def load(source: str | None):
    if source is None:
        source = DEFAULT_URL
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source) as response:
            return json.load(response)
    with open(source) as file:
        return json.load(file)


def rows(pairs):
    """Pack (name, code) pairs into source lines of several entries each."""
    entries = [f'("{name}", 0x{code:04x}),' for name, code in pairs]
    lines = []
    for start in range(0, len(entries), 6):
        lines.append("    " + " ".join(entries[start : start + 6]))
    return "\n".join(lines)


def main() -> None:
    data = load(sys.argv[1] if len(sys.argv) > 1 else None)
    meta = data.pop("METADATA")
    version = meta.get("version", "unknown")

    qualified = {}
    bare = {}
    for key, value in data.items():
        code = int(value["code"], 16)
        family, _, name = key.partition("-")
        qualified_key = normalize(key)
        # the old "nf-" prefixed spelling (Nerd Fonts v2 naming) normalizes
        # to the same key, so both spellings share one entry
        qualified[qualified_key.removeprefix("nf")] = code

        bare_key = normalize(name)
        current = bare.get(bare_key)
        if current is None or RANK.get(family, 99) < RANK.get(current[1], 99):
            bare[bare_key] = (code, family)

    sys.stdout.write(
        f"""//! Generated by `utils/gen_icons.py` from the Nerd Fonts glyph
//! names (glyphnames.json {version}, MIT license,
//! https://github.com/ryanoasis/nerd-fonts). Do not edit by hand —
//! regenerate with `just icons`.

/// Every glyph under its normalized qualified name ("md-power_off" →
/// "mdpower"; the v2 "nf-" prefix normalizes away). Sorted by name for
/// binary search.
#[rustfmt::skip]
pub(super) static QUALIFIED: &[(&str, u32)] = &[
{rows(sorted(qualified.items()))}
];

/// The glyphs under their family-less names ("power"), collisions between
/// sets resolved by the generator's family preference (Material Design
/// first). Sorted by name for binary search.
#[rustfmt::skip]
pub(super) static BARE: &[(&str, u32)] = &[
{rows(sorted((name, code) for name, (code, _) in bare.items()))}
];
"""
    )


if __name__ == "__main__":
    main()
